### ISSUE TITLE
Feature Request: Use keybinding

### ISSUE THREAD

**Issue by p1ho** [MontyLeGueux/Lutebot-2#10]
I've only really taken a deeper look at the code base today so my understanding is still limited.

I wonder if it's possible that we bind all 24 notes to an unused key on the keyboard or an imaginary gamepad, so instead of opening the console and entering the commands really quickly in succession in game (which pretty much render the bards immobile), it would instead fire those keystrokes.

(For example, from the game's perspective, it'll just see that the bard is moving while simultaneously pressing numpad keys really quickly.)

Not opening the console means that the bard would be mobile, which increases their survival rates and discourages them from camping in spawn.

**Comment by MontyLeGueux** [comment]
The game won't let you bind those 24 angles individually I'm afraid.

**Comment by p1ho** [comment]
I see, thanks for clarifying that!
