### ISSUE TITLE
Can't get project to build.

### ISSUE THREAD

**Issue by ScepticDope** [MontyLeGueux/Lutebot-2#5]
Could you perhaps add Sanford.Multimedia.Midi-master as a NuGet package? Or just included in the Repo? Its not actually included in your project and I can't seem to find a matching version of it. Also could not figure out a version from your `.csproj` file.

I got this one: https://github.com/tebjan/Sanford.Multimedia.Midi
and placed in the location you have it locally: https://github.com/MontyLeGueux/Lutebot-2/blob/91c85f38d0a1f3125ef6f3983562238f536f140f/LuteBot/LuteBot.csproj#L200 but it seems to be a different version.

I get a whole list of problems when trying to build the project. Do you have a custom version of Sanford.Multimedia.Midi?

![Capture](https://user-images.githubusercontent.com/46745973/59032592-f9c52780-8866-11e9-9743-d3d6136ffa64.PNG)

Also a readme with a bit of background on your project would be helpful.

**Comment by ScepticDope** [comment]
Think I might have found it you did not only use `Sanford.Multimedia.Midi` but also `Sanford.Multimedia` which seems part of the demo project from here: https://www.codeproject.com/Articles/6228/C-MIDI-Toolkit

*edit* No good, still using a different version of `Sanford.Multimedia.Midi-master`. Getting the same errors cause of the missing code.

**Comment by garrettluskey** [comment]
You can reference the .dll from the current one here https://drive.google.com/file/d/1thdENwlP75TlXWBB7xVpMZ0tZpUb6_pR/view

**Comment by p1ho** [comment]
@ScepticDope @garrettluskey 
I was running into the same issue today. the [`Sanford.Multi.Media` on Nuget](https://www.nuget.org/packages/Sanford.Multimedia.Midi/) does not have the methods the project is using. (For example, [`Sequencer.UpdateMutedTracks()`](https://github.com/MontyLeGueux/Lutebot-2/blob/master/LuteBot/Core/Midi/MidiPlayer.cs#L64) is not found using the Nuget version)

If we're referencing the `.dll`, is there a reason why it's not part of the repo?

EDIT: I understand putting dll file on GitHub is bad, I'm just trying to think of a better way of referencing this dependency. I mean, the google drive link is obviously not a good and reliable source for the dll file.

**Comment by walnutfalls** [comment]
I would feel a lot more comfortable using Lutebot if I could see the Sanford library source, or know thatit was from Nuget. As it is, literally anything can be in that dll. I took a very quick look with dotPeek, seems fine from the very few classes I looked at, but still.
